create database if not exists symbols;
use symbols;
CREATE TABLE IF NOT EXISTS titles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    isin VARCHAR(255),
    type VARCHAR(5),
    exchange VARCHAR(255),
    sectorYF VARCHAR(255),
    sectorMW VARCHAR(255),
    sectorND VARCHAR(255),
    industryYF VARCHAR(255),
    industryMW VARCHAR(255),
    industryND VARCHAR(255),
    details VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS stocks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    isin VARCHAR(12),
    symbolYF VARCHAR(10),
    symbolMW VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS indices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    symbolSQ VARCHAR(10),
    symbolYF VARCHAR(10),
    symbolMW VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS commodities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    symbolSQ VARCHAR(10),
    symbolYF VARCHAR(10),
    symbolMW VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS currencies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    symbolSQ VARCHAR(10),
    symbolYF VARCHAR(10),
    symbolMW VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS classificationsYF (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sector VARCHAR(50),
    industry VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS classificationsMW (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sector VARCHAR(50),
    industry VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS symbolsMW (
    id INT AUTO_INCREMENT PRIMARY KEY,
    isin VARCHAR(255),
    title VARCHAR(255),
    symbol VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS currentAssets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titleSQ VARCHAR(255) NOT NULL,
    symbolSQ VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS candidates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titleSQ VARCHAR(50),
    isin VARCHAR(12),
    type VARCHAR(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS candidatesoutliers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titleSQ VARCHAR(50),
    isin VARCHAR(12),
    type VARCHAR(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;
