// Generated by Selenium IDE
package shared.SQ;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import java.util.*;

import shared.Session;
import shared.SQ.SQframes;

public class SQlogin
{
  @Test
  public static void doSQlogin(String userName, String password, WebDriver driver)
  {
    System.out.println("SQ: do login");
    String id,xpath,linkText;
    try
    {
      xpath="//span[text()='LOGIN']";
      try
      {
        driver.findElement(By.xpath(xpath)).click();
      }
      catch(Exception e)
      {
        System.out.println("doSQlogin() failed: xpath="+xpath);
        Session.tearDownOnError(driver);
      }
      linkText="Login Bank";
      try
      {
        driver.findElement(By.linkText(linkText)).click();
      }
      catch(Exception e)
      {
        System.out.println("doSQlogin() failed: linkText="+linkText);
        Session.tearDownOnError(driver);
      }
      driver.switchTo().defaultContent();
      id="usernameText";
      try
      {
        driver.findElement(By.id(id)).sendKeys(userName);
      }
      catch(Exception e)
      {
        System.out.println("doSQlogin() failed: id="+id);
        Session.tearDownOnError(driver);
      }
      id="passwordText";
      try
      {
        driver.findElement(By.id(id)).sendKeys(password);
      }
      catch(Exception e)
      {
        System.out.println("doSQlogin() failed: id="+id);
        Session.tearDownOnError(driver);
      }
      id="loginText";
      try
      {
        driver.findElement(By.id(id)).click();
      }
      catch(Exception e)
      {
        System.out.println("doSQlogin() failed: id="+id);
        Session.tearDownOnError(driver);
      }
      System.out.println("SQ: login done");
    }
    catch(Exception e)
    {
      System.out.println("doSQlogin() failed");
      Session.tearDownOnError(driver);
    }
  }
}
