// Generated by Selenium IDE
package shared.EN.paris;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import java.util.*;

import shared.Session;

public class urls
{
  @Test
  public static void base(String userName, String password,WebDriver driver)
  {
  }

  @Test
  public static void goToYFmyPortfolio(WebDriver driver)
  {
    String id,xpath,linkText;
    System.out.println("YF: going to My Portfolio");
    while(true)
    {
      linkText="My Portfolio";
      try
      {
        driver.findElement(By.linkText(linkText)).click();
        System.out.println("YF: arrived at My Portfolio");
      }
      catch(Exception e)
      {
        System.out.println("goToYFmyPortfolio() failed: linkText="+linkText);
        Session.tearDownOnError(driver);
      }
      break;
    }
  }

  @Test
  public void deleteYFportfolio(String portfolioName,WebDriver driver)
  {
    System.out.println("YF: delete portfolio");
    String id,xpath,linkText;
    xpath="//a[normalize-space(text())='"+portfolioName+"']";
    if(driver.findElement(By.xpath(xpath)).getText() != "")
    {
      while(true)
      {
        try
        {
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//*[@data-test='dropdown']/div/span";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//*[@data-test='dropdown']/*[@id='dropdown-menu']/ul/li/button/span[text()='Delete Portfolio']";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//span[text()='Confirm']";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          System.out.println("YF: deleted portfolio");
          break;
        }
        catch(Exception e)
        {
          System.out.println("deleteYFportfolio() failed");
          Session.tearDownOnError(driver);
        }
        break;
      }
    }
  }
}
