// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import java.util.List;
//import java.util.*;

import shared.Session;

public class books
{
  static String xpathTopics =        "/html/body/div[2]/div[2]/div/div[1]/div[2]/div";
  static String xpathStudySessions = "/div";

  public static int countModules(WebDriver driver)
  {
    System.out.println("counting Modules in book");
    List<WebElement> listModules = driver.findElements(By.xpath("/html/body/div[2]/div[2]/div/div[1]/div[2]/div/div/div"));
    return listModules.size();
  }

  public static List<WebElement> getModules(WebDriver driver)
  {
    System.out.println("getting Modules in book");
    List<WebElement> listModules = driver.findElements(By.xpath("/html/body/div[2]/div[2]/div/div[1]/div[2]/div/div/div"));
    return listModules;
  }
}
