// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
//import java.util.*;

import shared.Session;

public class login
{
  public static Boolean doLogin(String username, String password, WebDriver driver)
  {
    System.out.println("do login");
    try
    {
      driver.switchTo().frame("iamFrame");
      driver.findElement(By.name("username")).sendKeys(username);
      driver.findElement(By.name("password")).sendKeys(password);
      driver.findElement(By.xpath("//span[text()='Sign In']")).click();
      Session.timeout(5000);
      return true;
    }
    catch(Exception e)
    {
      System.out.println("login failed, retrying");
      System.out.println(e);
      return false;
    }
    
  }
}
