// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
//import java.util.*;

import shared.Session;

public class navigate
{
  public static void selectStudyTools(WebDriver driver)
  {
    System.out.println("select Study Tools");
    driver.findElement(By.xpath("//span[text()='Study Tools']")).click();
  }

  public static void selectSchweserNotes(WebDriver driver)
  {
    System.out.println("select SchweserNotes");
    driver.findElement(By.xpath("//span[text()='SchweserNotes']")).click();
  }

  public static void selectSchweserNotesBook(int number,WebDriver driver)
  {
    System.out.println("select Schweser Notes Book");
    String SchweserNotesBook = "SchweserNotes - Book "+number;
    String xpath = "//a[text()='"+SchweserNotesBook+"']";
    driver.findElement(By.xpath(xpath)).click();
  }

  public static Boolean selectCourse(String courseId, WebDriver driver)
  {
    System.out.println("selectCourse");
    driver.switchTo().defaultContent();

    try
    {
      String id = "//*[@id='26021851']";
      driver.findElement(By.xpath(id)).click();
      return true;
    }
    catch(Exception e)
    {
      System.out.println("selectCourse failed");
      System.out.println(e);
      return false;
    }
  }
}
