// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import java.util.List;

import shared.Session;

public class operations
{
  public static void unfold(WebElement element,WebDriver driver)
  {
    System.out.println("unfold");
    element.click();
  }

  public static void fold(WebElement element,WebDriver driver)
  {
    System.out.println("fold");
    element.click();
  }

  public static Boolean checkFoldStatus(WebElement topic,WebDriver driver)
  {
    try
    {
      System.out.println("check FoldStatus");
      topic.findElement(By.xpath("//[open='']"));
      System.out.println("unfolded");
      return true;
    }
    catch(Exception e)
    {
      System.out.println("folded");
      return false;
    }
  }
}
