// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
//import java.util.*;

import shared.Session;

public class course
{
  public static Boolean selectCourse(String username, String password, WebDriver driver)
  {
    System.out.println("selecting course");
    try
    {
//      driver.switchTo().defaultContent();
      driver.findElement(By.xpath("//*a[text()='CFA Level II February']")).click();
      return true;
    }
    catch(Exception e)
    {
      System.out.println("selecting course failed");
      System.out.println(e);
      return false;
    }
    
  }
}
