// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import java.util.List;
//import java.util.*;

import shared.Session;

public class studySessions
{
  static String xpath = "/button";

  public static int count(WebElement topic,WebDriver driver)
  {
    System.out.println("counting StudySessions");
    List<WebElement> listStudySessions = topic.findElements(By.xpath(xpath));
    return listStudySessions.size();
  }

  public static List<WebElement> get(WebElement topic,WebDriver driver)
  {
    System.out.println("getting StudySessions");
    List<WebElement> listStudySessions = topic.findElements(By.xpath(xpath));
    return listStudySessions;
  }
}
