// Generated by Selenium IDE
package shared.KS;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import java.util.List;

import shared.Session;

public class topics
{
  static String xpath = "//*[@id='root']/div[2]/div/div[1]/div[2]/div";

  public static int count(WebDriver driver)
  {
    System.out.println("counting Topics");
    List<WebElement> listTopics = driver.findElements(By.xpath(xpath));
    return listTopics.size();
  }

  public static List<WebElement> get(WebDriver driver)
  {
    System.out.println("getting Topics");
    List<WebElement> listTopics = driver.findElements(By.xpath(xpath));
    return listTopics;
  }
}
