// Generated by Selenium IDE
package shared.DB;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.SQLException;

import shared.Session;
import shared.Environment;

public class select
{
  static String statement;
  static String c1,c2,c3,c4,c5;
  static String tableName,column;
  static Connection connectionDB;

  public static class c1
  {
    String blah = "blah";
    public static ResultSet all(Connection connectionDB,String column,String tableName)
    {
      String statement = "SELECT "+column+" FROM "+tableName;
      return DB.executeQuery(connectionDB,statement);
    }
    public static class where
    {
      public static class c
      {
        public static class equals
        {
          public static ResultSet v(Connection connectionDB,String searchC,String tableName,String c,String v)
          {
            statement = "SELECT "+searchC+" FROM "+tableName+" WHERE "+c+"='"+v+"'";
            return DB.executeQuery(connectionDB,statement);
          }
        }

        public static class notEquals
        {
          public static ResultSet v(Connection connectionDB, String searchC,String tableName,String c,String v)
          {
            statement = "SELECT "+searchC+" FROM "+tableName+" WHERE "+c+"!='"+v+"'";
            return DB.executeQuery(connectionDB,statement);
          }
	}
      }
    }

    public static class c2
    {
      public static ResultSet all(Connection connectionDB,String column,String tableName)
      {
        statement = "SELECT "+column+" FROM "+tableName;
        return DB.executeQuery(connectionDB,statement);
      }
  
      public static class where
      {
        public static class c
        {
          public static class equals
          {
            public static ResultSet v(Connection connectionDB,String searchC,String tableName,String c,String v)
            {
              statement = "SELECT "+searchC+" FROM "+tableName+" WHERE "+c+"='"+v+"'";
              return DB.executeQuery(connectionDB,statement);
            }
          }
  
          public static class notEquals
          {
            public static ResultSet v(Connection connectionDB, String searchC,String tableName,String c,String v)
            {
              statement = "SELECT "+searchC+" FROM "+tableName+" WHERE "+c+"!='"+v+"'";
              return DB.executeQuery(connectionDB,statement);
            }
          }
        }
      }
    }
  }
}
