// Generated by Selenium IDE
package shared.DB;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.SQLException;

import shared.Session;
import shared.Environment;

public class truncate
{
  static String statement;
  public class table
  {
    public static Boolean get(Connection connectionDB,String tableName)
    {
      statement = "TRUNCATE TABLE "+tableName;
      System.out.println(statement);
      return DB.execute(connectionDB,statement);
    }
  }
}
