// Generated by Selenium IDE
package shared.YF;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import java.util.*;

import shared.Session;
import shared.Environment;

public class MDfunctions
{
  static int sleepTimeMD = Environment.getSleepTimeMD();

  @Test
  public static String getSectorMD(String symbolYF,int retryCount,WebDriver driver)
  {
    String sector ;
    try
    {
      WebElement profileYFtable = driver.findElement(By.id("Col1-0-Profile-Proxy"));
      sector = profileYFtable.findElement(By.xpath("//section/div[1]/div/div/p[2]/span[2]")).getText();
    }
    catch(Exception e)
    {
      System.out.println("getSectorYF: no profile found for: "+symbolYF);
      sector = "void";
    }
    return sector;
  }
}
