// Generated by Selenium IDE
package shared.YF;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import java.util.*;

import shared.Session;

public class YFlogin
{
  @Test
  public static void doYFlogin(String userName, String password, int retryCount, WebDriver driver)
  {
    System.out.println("YF: calling home");
    int count=0;
    String id,xpath,linkText;
    while(true)
    {
      try
      {
        id="header-signin-link";
        try
        {
            driver.findElement(By.id(id)).click();
        }
        catch(Exception e)
        {
          System.out.println("doYFlogin failed: id="+id);
          Session.tearDownOnError(driver);
        }
        id="login-username";
        try
        {
            driver.findElement(By.id("login-username")).sendKeys("cbeerli1980@gmail.com");
        }
        catch(Exception e)
        {
          System.out.println("doYFlogin failed: id="+id);
          Session.tearDownOnError(driver);
        }
        id="login-signin";
        try
        {
            driver.findElement(By.id(id)).click();
        }
        catch(Exception e)
        {
          System.out.println("doYFlogin failed: id="+id);
          Session.tearDownOnError(driver);
        }
        id="login-passwd";
        try
        {
            driver.findElement(By.id(id)).sendKeys("SMFlist1!");
        }
        catch(Exception e)
        {
          System.out.println("doYFlogin failed: id="+id);
          Session.tearDownOnError(driver);
        }
        id="login-signin";
        try
        {
            driver.findElement(By.id(id)).click();
        }
        catch(Exception e)
        {
          System.out.println("doYFlogin failed: id="+id);
          Session.tearDownOnError(driver);
        }
        break;
      }
      catch(Exception e)
      {
        if(++count == retryCount);
        System.out.println("doYFlogin() failed");
        Session.tearDownOnError(driver);
      }
      System.out.println("YF: fetched home");
      break;
    }
  }

  @Test
  public static void goToYFmyPortfolio(int retryCount, WebDriver driver)
  {
    String id,xpath,linkText;
    System.out.println("YF: going to My Portfolio");
    int count=0;

    while(true)
    {
      linkText="My Portfolio";
      try
      {
        driver.findElement(By.linkText(linkText)).click();
        System.out.println("YF: arrived at My Portfolio");
      }
      catch(Exception e)
      {
        if(++count == retryCount);
        System.out.println("goToYFmyPortfolio() failed: linkText="+linkText);
        Session.tearDownOnError(driver);
      }
      break;
    }
  }

  @Test
  public void deleteYFportfolio(String portfolioName,int retryCount, WebDriver driver)
  {
    System.out.println("YF: delete portfolio");
    String id,xpath,linkText;
    int count=0;
    xpath="//a[normalize-space(text())='"+portfolioName+"']";
    if(driver.findElement(By.xpath(xpath)).getText() != "")
    {
      while(true)
      {
        try
        {
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//*[@data-test='dropdown']/div/span";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//*[@data-test='dropdown']/*[@id='dropdown-menu']/ul/li/button/span[text()='Delete Portfolio']";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          xpath="//span[text()='Confirm']";
          try
          {
            driver.findElement(By.xpath(xpath)).click();
          }
          catch(Exception e)
          {
            System.out.println("deleteYFportfolio failed: xpath="+xpath);
            Session.tearDownOnError(driver);
          }
          System.out.println("YF: deleted portfolio");
          break;
        }
        catch(Exception e)
        {
          if(++count == retryCount);
          System.out.println("deleteYFportfolio() failed");
          Session.tearDownOnError(driver);
        }
        break;
      }
    }
  }
}
